name: ğŸš€ Deploy website on push
on: push

jobs:
  web-deploy:
    name: ğŸ‰ Auto deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ğŸ“‚ Sync files
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete --exclude=".git" --exclude=".github"
        path: /
        remote_path: /home/justnear/sikuku.justnear.my.id/
        remote_host: sikuku.justnear.my.id
        remote_user: justnear
        remote_key: ${{ secrets.DEPLOY_KEY }}
